//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.16 at 07:42:17 PM CEST 
//


package URTO;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContractualContext complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContractualContext">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="clientCompanyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="contractualId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContractualContext", propOrder = {
    "clientCompanyCode",
    "contractualId"
})
public class ContractualContext {

    @XmlElement(required = true)
    protected String clientCompanyCode;
    @XmlElement(required = true)
    protected String contractualId;

    /**
     * Gets the value of the clientCompanyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientCompanyCode() {
        return clientCompanyCode;
    }

    /**
     * Sets the value of the clientCompanyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientCompanyCode(String value) {
        this.clientCompanyCode = value;
    }

    /**
     * Gets the value of the contractualId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractualId() {
        return contractualId;
    }

    /**
     * Sets the value of the contractualId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractualId(String value) {
        this.contractualId = value;
    }

}
