//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.16 at 07:42:17 PM CEST 
//


package URTO;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the URTO package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: URTO
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Call }
     * 
     */
    public Call createCall() {
        return new Call();
    }

    /**
     * Create an instance of {@link Caller }
     * 
     */
    public Caller createCaller() {
        return new Caller();
    }

    /**
     * Create an instance of {@link ContractualContext }
     * 
     */
    public ContractualContext createContractualContext() {
        return new ContractualContext();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link LocationHeader }
     * 
     */
    public LocationHeader createLocationHeader() {
        return new LocationHeader();
    }

    /**
     * Create an instance of {@link SystemInformation }
     * 
     */
    public SystemInformation createSystemInformation() {
        return new SystemInformation();
    }

    /**
     * Create an instance of {@link Contact }
     * 
     */
    public Contact createContact() {
        return new Contact();
    }

    /**
     * Create an instance of {@link CallResponse }
     * 
     */
    public CallResponse createCallResponse() {
        return new CallResponse();
    }

    /**
     * Create an instance of {@link ContextObject }
     * 
     */
    public ContextObject createContextObject() {
        return new ContextObject();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link VehicleAccidentContext }
     * 
     */
    public VehicleAccidentContext createVehicleAccidentContext() {
        return new VehicleAccidentContext();
    }

    /**
     * Create an instance of {@link ServiceRequest }
     * 
     */
    public ServiceRequest createServiceRequest() {
        return new ServiceRequest();
    }

    /**
     * Create an instance of {@link KeyValuePair }
     * 
     */
    public KeyValuePair createKeyValuePair() {
        return new KeyValuePair();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link EcallRequest }
     * 
     */
    public EcallRequest createEcallRequest() {
        return new EcallRequest();
    }

    /**
     * Create an instance of {@link VehicleDiagContext }
     * 
     */
    public VehicleDiagContext createVehicleDiagContext() {
        return new VehicleDiagContext();
    }

    /**
     * Create an instance of {@link RequestObject }
     * 
     */
    public RequestObject createRequestObject() {
        return new RequestObject();
    }

    /**
     * Create an instance of {@link TestimonialRequest }
     * 
     */
    public TestimonialRequest createTestimonialRequest() {
        return new TestimonialRequest();
    }

    /**
     * Create an instance of {@link AssistanceRequest }
     * 
     */
    public AssistanceRequest createAssistanceRequest() {
        return new AssistanceRequest();
    }

    /**
     * Create an instance of {@link Recipient }
     * 
     */
    public Recipient createRecipient() {
        return new Recipient();
    }

    /**
     * Create an instance of {@link Vehicle }
     * 
     */
    public Vehicle createVehicle() {
        return new Vehicle();
    }

}
