//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.16 at 07:42:22 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://not.ima.tm.fr/telematic", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package SOS;
